<a href="https://colab.research.google.com/github/JorgeZarama/python/blob/main/01MIAR_08_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="img/viu_logo.png" width="200">

## 01MIAR - NumPy

![logo](img/python_logo.png)

*Ivan Fuertes*

# NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [1]:
#importar libreria
import numpy as np

## Performance Sample, NumPy vs Plain Python

In [ ]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list2 = [x * 2 for x in my_list]

CPU times: user 310 ms, sys: 76.9 ms, total: 387 ms
Wall time: 388 ms


In [ ]:
my_arr = np.arange(10000000)  # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: user 6.85 ms, sys: 8.29 ms, total: 15.1 ms
Wall time: 19.4 ms


## Formas de crear ndarrays

In [ ]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [ ]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [ ]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2))    # array a partir de una secuencia(range) 1D

[100  10   1]
[2 4 6 8]


In [ ]:
# Generar arrays con valores fijos
print(np.zeros(2))       # 1D
print(np.ones((2,2)))    # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),3)) # matrix 5x2
print(np.eye(3))         # matrix identity

[0. 0.]
[[1. 1.]
 [1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Obtener información sobre ndarray

In [ ]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)

[ 2 71  0 34]


In [ ]:
print(my_ndarray.argmax())    # índice del valor más alto
print(np.amax(my_ndarray))

print(my_ndarray.argmin())    # índice del valor más bajo
print(np.amin(my_ndarray))

print(my_ndarray.nonzero())   # retorna los índices de los elementos distintos a 0

1
71
2
0
(array([0, 1, 3]),)


In [ ]:
my_ndarray = np.full((5,2, 2),-3) # matrix 5x2
print(my_ndarray)

print(my_ndarray.size)        # número de elementos
print(my_ndarray.shape)       # dimensiones
print(my_ndarray.ndim)        # número de dimensiones

[[[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]]
20
(5, 2, 2)
3


#### Redimensionar los datos

In [ ]:
my_ndarray = np.array([[10, 71, 21, 19, 213, 412, 111, 98]])  # matrix 1x8
print(my_ndarray)
print(my_ndarray.shape)
print(my_ndarray.ndim)

[[ 10  71  21  19 213 412 111  98]]
(1, 8)
2


In [ ]:
new_dims = my_ndarray.reshape(2, 4)  # cambiar las dimensiones a 4x2
print(new_dims)

[[ 10  71  21  19]
 [213 412 111  98]]


In [ ]:
new_dims = my_ndarray.reshape(4, 2)  # cambiar las dimensiones a 2x4
print(new_dims)

[[ 10  71]
 [ 21  19]
 [213 412]
 [111  98]]


In [ ]:
x = np.array([100, 10, 1]).reshape(3,1)
print(x.shape)
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [ ]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(new_dims.flatten()) #aplanar na matriz a una dimensión

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [ ]:
# reducir
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(2, -1))    # el segundo valor se infiere del primero

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## Manipulación de ndarrays

In [ ]:
# Cambiar ejes
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.swapaxes(0,1))#cambio ejes, transponer

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [ ]:
# Flip
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(np.flip(new_dims)) #espejo

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [ ]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(array1)

[ 2  9 10 17]


In [ ]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]

print(np.hstack((a1,a2))) # una al lado de la otra
print(np.hstack((a1,a2)).shape)

print(np.vstack((a1,a2))) # una encima de la otra
print(np.vstack((a1,a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [ ]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,2, axis=1)) # divide array en 2 partes iguales
print(np.array_split(array,3)) # divide array en 3 partes "iguales"
print(np.array_split(array,[2],axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [3]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,[3], axis = 0)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [ ]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0))  # divide array por la fila 1 y 2

print(np.array_split(array, [1, 3], axis = 1))  # divide array por la columna 1 y 2
# # axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

# Índices y slicing
- De manera análoga a índices y slicing para listas

In [ ]:
array = np.arange(10, 16)
print(array)
print(array[2])    # acceso unidimensional
print(array[:-1])  # slice

[10 11 12 13 14 15]
12
[10 11 12 13 14]


In [5]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna
print(array[2][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
10


In [6]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[1,2,4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
34


#### NumPy es row major

In [7]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3)  # by default, row major
print(row_major)

[[1 2 3]
 [4 5 6]]


In [8]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C')  # by default, row major
print(row_major)

col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F')  # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


#### Slice

In [9]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)
print(array[:,0])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[ 0  9 18 27 36 45 54 63 72]


In [10]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


#### Diferencias entre índices y slicing en listas y ndarrays:
- ¡Retornan una referencia, no una copia!

In [11]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2]  # devuelve una copia
print(my_copy)
my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [12]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5]  # devuelve una referencia
print(array)
print(my_copy)
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [13]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy()  # hay que hacer la copia explicitamente
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


- Permite asignar valores a un corte

In [14]:
array = np.arange(10)
print(array)

array[0:3] = -1
print(array)

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1  3  4  5  6  7  8  9]


- Slicing condicionales (mask)

In [15]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array < 0
print(mask)

print(array[mask])

array[mask] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[ True  True  True False False False False]
[-3 -2 -1]
[0 0 0 0 1 2 3]


In [16]:
array = np.arange(-3,4)
print(array)

array[array < 0] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [17]:
# slicing condicional aca si DEVUELVE UNA COPIA

array = np.arange(-3,4)
print(array)

mask = array % 2 == 0
print(mask)

array_par = array[mask]  # devuelve una copia
print(array_par)

array_par[0] = -10
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


In [ ]:
# slicing condicional
array = np.arange(-3,4)
mask = array % 2 == 0
print(mask)
print(array)
print(array[mask])

array[mask] = 10 # ??
print(array)

mask = array == 10
array[mask] = 0 # ??
print(array)

[False  True False  True False  True False]
[-3 -2 -1  0  1  2  3]
[-2  0  2]
[-3 10 -1 10  1 10  3]
[-3  0 -1  0  1  0  3]


- Acceso a múltiples valores con listados de índices

In [18]:
array = np.arange(-10,0)
print(array)
print(array[[2,3,1]])

ar = array[[2,3,1]] # slice, copia
print(ar)
ar[0] = 999
print(ar)
print(array)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[-8 -7 -9]
[-8 -7 -9]
[999  -7  -9]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


# Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [ ]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)

lista += [1]
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [ ]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4) * 2
print(array)

array += 10
print(array)

[2. 2. 2. 2.]
[12. 12. 12. 12.]


In [ ]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[2.         1.         0.66666667 0.5       ]


## Broadcasting

Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande -> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

## Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [ ]:
# ejemplos de operadores
array = np.arange(5)
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])

print(array1)
print(array2)

print(np.greater(array1,array2))
print(np.less(array2, array1))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


# Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o >0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

In [ ]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [ ]:
# any vs all
array1 = np.arange(-15,-5).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores <> 0

[[-15 -14 -13 -12 -11]
 [-10  -9  -8  -7  -6]]
True
True


In [ ]:
# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


# Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multipliacción de matrices, cálculo del determinante, factorizaciones...


| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |

In [ ]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)

print(A)
print(B)

print(np.matmul(A,B))
print(np.dot(A, B))
print(A @ B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [ ]:
import numpy.linalg as linalg
import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x

a = np.array([ [3,2,5], [1,-3,-1],[2,-1,12] ])
b = np.array([12,2,32])

print(a)
print(b)
x,y,z = linalg.solve(a,b)
print(f'x={x} y={y} z={z}')

print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x - 3*y - z, 2))
print(math.isclose(2*x -y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [ ]:
#matriz identidad
I = np.identity(4)
print(I)

A = np.arange(16).reshape(4,4)
print(A)

print(np.matmul(A,I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


# Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [ ]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
# mask con los elementos menores de 1
mask = np.where(prices < 1, True, False)# seteo el valor para los casos que se cumpla y para los casos que no se cumpla
print(mask)
print(prices[mask])

print(np.where(prices < 1, 1.0, prices))

[ True False False False  True]
[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]


In [ ]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [ ]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

[  10.   12. -143.    0.    1.   -3.]


In [19]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True

print(credits)
print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [ ]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)

rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)

daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)

final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


# Números aleatorios
- Python módulo random

In [23]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores

0.6023711666243262
4
0.7064996422821868


In [27]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)

'Pikachu'

## NumPy.random
- Generar fácilmente listas con valores aleatorios

In [28]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.6179618743063142
2
[[4 2 0 2]
 [4 2 0 2]]


In [29]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[ 0.65172199  1.01922689]
 [ 0.37169419  1.2932693 ]
 [-3.13094189 -0.76628228]
 [ 0.07828769  1.27179843]]


In [30]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

1
0.3661716764249767
[[4 4]
 [0 3]]


## Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [31]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())

print()

for i in range(5):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())
    print(np.random.rand())

0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223


# Escritura y lectura de ndarrays a archivos
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [33]:
# escribir a archivo
import os
ruta = os.path.join("o_values_array.npy")

values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)

[[4 2 6]
 [4 3 0]
 [7 5 5]]


In [34]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[4 2 6]
 [4 3 0]
 [7 5 5]]


In [36]:
# escribir y cargar múltiples arrays
ruta = os.path.join("o_array_group.npz")

values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz

In [37]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)

print(type(npzfile.files))

for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
    print(npzfile[key])

<class 'list'>
[[0 1 0]
 [7 2 6]
 [3 7 8]]
[[2 2]
 [3 1]]
[[10  7  9  2]
 [ 7  5  3  0]
 [ 5 14 15  4]
 [11 11 11  3]]


### ¿Por qué molestarse con .npy?
- Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
- ¿Para qué escribir los datos de nuevo?

In [51]:
ruta_csv = os.path.join("fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)

ruta_npy = os.path.join("o_fdata.npy")#Ocupa menos memoria
np.save(ruta_npy, data_array)

In [52]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data,  dtype = np.int8).reshape(1000,1000)

191 ms ± 39.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [53]:
%%timeit
data = np.load(ruta_npy)

404 µs ± 16.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")

253 ms ± 58.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### velocidad + simplicidad vs memoria

## Ejercicios

- Ejercicios para practicar NumPy: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
- Con pistas: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints.md
- Soluciones en: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md